In [1]:
import nashpy as nash
import numpy as np
P_B=np.array([[2,0],[0,1]])
P_S=np.array([[1,0],[0,2]])
BoS=nash.Game(P_B,P_S)
BoS

Bi matrix game with payoff matrices:

Row player:
[[2 0]
 [0 1]]

Column player:
[[1 0]
 [0 2]]

In [2]:
p_B_sigma=[1,0]
p_S_sigma=[0,1]
BoS[p_B_sigma,p_S_sigma]

array([0, 0])

In [3]:
eqs = BoS.support_enumeration()
list(eqs)

[(array([1., 0.]), array([1., 0.])),
 (array([0., 1.]), array([0., 1.])),
 (array([0.66666667, 0.33333333]), array([0.33333333, 0.66666667]))]

In [4]:
eqs1=BoS.vertex_enumeration()
list(eqs1)

[(array([1.11022302e-16, 1.00000000e+00]), array([0., 1.])),
 (array([0.66666667, 0.33333333]), array([0.33333333, 0.66666667])),
 (array([1., 0.]), array([1.00000000e+00, 1.11022302e-16]))]

It has 2 Nash Equilibria : (B,B) and (S,S)

Stag Hunt can also be represented as above.