In [1]:
import nashpy as nash
import numpy as np
P1=np.array([[1,-1],[-1,1]])
P2=np.array([[-1,1],[1,-1]])
matching_pennies=nash.Game(P1,P2)
matching_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [2]:
p1_sigma=[1,0]
p2_sigma=[0,1]
matching_pennies[p1_sigma,p2_sigma]

array([-1,  1])

In [3]:
eqs = matching_pennies.support_enumeration()
list(eqs)

[(array([0.5, 0.5]), array([0.5, 0.5]))]

In [4]:
eqs1=matching_pennies.vertex_enumeration()
list(eqs1)

[(array([0., 1.]), array([0.66666667, 0.33333333])),
 (array([0.5, 0.5]), array([0.5, 0.5]))]

Hence, it has no Nash Equilibrium.