In [1]:
import nashpy as nash
import numpy as np
P1=np.array([[2,0],[3,1]])
P2=np.array([[2,3],[0,1]])
prisoner_dilemma=nash.Game(P1,P2)
prisoner_dilemma

Bi matrix game with payoff matrices:

Row player:
[[2 0]
 [3 1]]

Column player:
[[2 3]
 [0 1]]

In [2]:
p1_sigma=[1,0]
p2_sigma=[0,1]
prisoner_dilemma[p1_sigma,p2_sigma]

array([0, 3])

In [3]:
eqs = prisoner_dilemma.support_enumeration()
list(eqs)

[(array([0., 1.]), array([0., 1.]))]

In [4]:
eqs1=prisoner_dilemma.vertex_enumeration()
list(eqs1)

[(array([2.77555756e-17, 1.00000000e+00]),
  array([2.77555756e-17, 1.00000000e+00])),
 (array([0., 1.]), array([0., 1.]))]

All other games like joint project, duopoly, arms race, tragedy of commons can be represented by above.